---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    one: one
  name: e-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      one: one
  template:
    metadata:
      labels:
        one: one
    spec:
      volumes:
      - name: e-nfs-volume
        nfs:
          server: rock0 # Change this!
          path: /mnt/usb256
      - name: e-pv-volume
        persistentVolumeClaim: 
          claimName: 1-pvc
      containers:
      - name: e-bash
        image: bash
        command: [ "top" ]
        volumeMounts:
        - mountPath: "/var/run/4-nfs"
          name: e-nfs-volume
        - mountPath: "/var/run/1-pv"
          name: e-pv-volume
...
