---
apiVersion: v1
kind: Pod
metadata:
  name: g-pod-file
  labels:
    taranto.dev/app: k8s-demo
spec:
  containers:
  - name: g-file-one 
    image: bash
    command: [ "watch", "uptime" ]
    volumeMounts: 
    - name: vol-config
      mountPath: /etc/config
  volumes:
  - name: vol-config
    configMap:
      name: g-configmap-file
  restartPolicy: Never
...

