---
apiVersion: batch/v1
kind: Job
metadata:
  name: g-job-env
  labels:
    mysidlabs.com/app: k8s-demo
spec:
  template:
    spec:
      containers:
      - name: g-env-one 
        image: bash
        command: [ "bash", "-c",  "for x in {1..10}; do echo My favorite customer is $BEST_CUSTOMER!; sleep .5; done" ]
        env:
        - name: BEST_CUSTOMER
          valueFrom:
            configMapKeyRef:
              name: g-configmap-literal
              key: customer
      restartPolicy: Never
...

