---
# from test-branch
apiVersion: v1
kind: Pod
metadata:
  name: g-pod-file
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: g-config
spec:
  containers:
  - name: g-file-one 
    image: bash
    command: [ "watch", "uptime" ]
    volumeMounts: 

    - name: vol-file
      mountPath: /etc/config-file
    - name: vol-literal
      mountPath: /etc/config-literal
  volumes:
  - name: vol-file
    configMap:
      name: g-configmap-file
  - name: vol-literal
    configMap:
      name: g-configmap-literal
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
...

