---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: x-pv
  labels:
    mysidlabs.com/app: k8s-demo
spec:
  storageClassName: b-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/x-pv
...
