---
kind: Pod
apiVersion: v1
metadata:
  name: d-web
  labels:
    app: k8s-demo
    tier: web
spec:
  containers:
    - name: web
      image: nginx
      ports:
      - name: http
        containerPort: 80
...
