---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: d-networking
  name: d-front
spec:
  replicas: 1
  selector:
    matchLabels:
      mysidlabs.com/example: d-front
  template:
    metadata:
      labels:
        mysidlabs.com/example: d-front
    spec:
      containers:
      - name: front
        image: staranto/my-toolkit:arm64
        command: [ "top" ]
...
