---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: d-networking
    mysidlabs.com/tier: web
  name: d-web
spec:
  replicas: 1
  selector:
    matchLabels:
      mysidlabs.com/example: d-web
  template:
    metadata:
      labels:
        mysidlabs.com/example: d-web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - name: http
          containerPort: 80
...
