---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: d-networking
    taranto.dev/tier: web
  name: d-web
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/example: d-web
  template:
    metadata:
      labels:
        taranto.dev/example: d-web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - name: http
          containerPort: 80
...
