---
kind: Pod
apiVersion: v1
metadata:
  name: d-web
  labels:
    taranto.dev/app: k8s-demo
    tier: web
spec:
  containers:
    - name: web
      image: nginx
      ports:
      - name: http
        containerPort: 80
...
---
kind: Service
apiVersion: v1
metadata:
  name: d-web-svc
spec:
  selector:
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  type: LoadBalancer
...
