---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    taranto.dev/app: simple-http
    taranto.dev/app.simple-http.role: counter-route
  name: counter
spec:
  host: ""
  port:
    targetPort: http
  to:
    kind: Service
    name: counter
    weight: 100
  wildcardPolicy: None
...
