---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    mysidlabs.com/app: simple-http
    mysidlabs.com/app.simple-http.role: counter-route
  name: counter
spec:
  # Empty provides a namespace-encoded URL.
  host: ""
  path: "/get"
  port:
    targetPort: http
  to:
    kind: Service
    name: counter
    weight: 100
  wildcardPolicy: None
...
