---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mysidlabs.com/app: k8s-demo
  name: c-dep-katy
spec:
  replicas: 1
  selector:
    matchLabels:
      mysidlabs.com/app: c-dep
  template:
    metadata:
      labels:
        mysidlabs.com/app: c-dep
    spec:
      containers:
      - name: c-katy
        image: staranto/k8s-demo-user
        imagePullPolicy: IfNotPresent
        command:
        - top
        securityContext:
          runAsUser: 3001
          runAsGroup: 3001
      - name: c-root
        image: staranto/k8s-demo-user
        imagePullPolicy: IfNotPresent
        command:
        - top
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
      - name: c-none
        image: staranto/k8s-demo-user
        imagePullPolicy: IfNotPresent
        command:
        - top
...

