---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: c-role-zach
  namespace: k8s-demo
rules:
- apiGroups:
  - "*"
  resources:
  - "pods"
  - "deploy"
  verbs:
  - get
  - list
  - watch
...
