---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-2
  labels:
    mysidlabs.com/app: k8s-demo
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-2"
...
