apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-dep-cache
  labels: 
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: e-targeted-deploy
spec:
  selector:
    matchLabels:
      mysidlabs.com/example: e-dep-antiaffinity
  replicas: 3
  template:
    metadata:
      labels:
        mysidlabs.com/example: e-dep-antiaffinity
        mysidlabs.com/tier: cache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: mysidlabs.com/tier
                operator: In
                values:
                - cache
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: e-redis
        image: redis
