apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-dep-web
  labels: 
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: e-targeted-deploy
spec:
  selector:
    matchLabels:
      mysidlabs.com/example: e-dep-affinity
  replicas: 3
  template:
    metadata:
      labels:
        mysidlabs.com/example: e-dep-affinity
        mysidlabs.com/tier: web
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: mysidlabs.com/tier
                operator: In
                values:
                - cache
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: e-web
        image: nginx
