---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: b-pvc
  labels:
    app: k8s-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
