---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: b-pvc
  labels:
    taranto.dev/app: k8s-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
...
