---
kind: Pod
apiVersion: v1
metadata:
  name: b-pod
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: b-storage
spec:
  containers:
  - name: b-one
    image: mysidlabs/k8s-demo-runner:0.1
    imagePullPolicy: Always
    env:
    - name: KUBERNETES_NS
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: b-vol
      mountPath: "/var/run/demo"
  terminationGracePeriodSeconds: 1
  volumes:
    - name: b-vol
      persistentVolumeClaim:
        claimName: b-pvc-pod
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: b-pvc-pod
  annotations:
    volume.beta.kubernetes.io/storage-class: b-sc-nfs
    volume.beta.kubernetes.io/storage-provisioner: openshift.org/aws-efs
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Mi
  storageClassName: b-sc-nfs
  volumeMode: Filesystem
...
