---
kind: Pod
apiVersion: v1
metadata:
  name: b-pod
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: b-storage
spec:
  containers:
  - name: b-one
    image: staranto/k8s-demo-runner:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: b-vol
      mountPath: "/var/run/b-vol"
  terminationGracePeriodSeconds: 1
  volumes:
    - name: b-vol
      persistentVolumeClaim:
        claimName: b-pvc
...
