---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: b-pv
  labels:
    taranto.dev/app: k8s-demo
spec:
  storageClassName: b-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/b-pv

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rock3
          #- k3d-k3s-default-worker-1
...
