---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: x-pv
  labels:
    taranto.dev/app: k8s-demo
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/x-pv"
...
