---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    taranto.dev/app: k8s-demo
  name: f-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/app: f-dep
  template:
    metadata:
      labels:
        taranto.dev/app: f-dep
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: f-limits
        image: bash
        command: [ "watch", "uptime" ]
        resources:
          limits:
            memory: "512Mi"
            cpu: "1500m"
          requests:
            memory: "256Mi"
            cpu: "500m"
      priorityClassName: f-pc-low 
...
