---
kind: Pod
apiVersion: v1
metadata:
  name: f-pod
  labels:
    taranto.dev/app: k8s-demo
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: f-one
      image: bash
      command: [ "watch", "uptime" ]
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
  priorityClassName: f-pc-low
...
