---
kind: Pod
apiVersion: v1
metadata:
  name: f-pod
  labels:
    taranto.dev/app: k8s-demo
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: f-one
      image: staranto/my-toolkit:arm64
      imagePullPolicy: Always
      command: [ "watch", "uptime" ]
      resources:
        limits:
          memory: "256Mi"
          cpu: "2000m"
        requests:
          memory: "128Mi"
          cpu: "1000m"
  priorityClassName: f-pc-medium
...
