apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-dep-cache
  labels: 
    taranto.dev/app: k8s-demo
    taranto.dev/section: e-targeted-deploy
spec:
  selector:
    matchLabels:
      taranto.dev/example: e-dep-antiaffinity
  replicas: 3
  template:
    metadata:
      labels:
        taranto.dev/example: e-dep-antiaffinity
        taranto.dev/tier: cache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: taranto.dev/tier
                operator: In
                values:
                - cache
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: e-redis
        image: redis
