---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-demo
  name: e-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-dep
  template:
    metadata:
      labels:
        app: e-dep
    spec:
      tolerations:
      - key: taranto.dev/month-end
        operator: Exists
        effect: NoSchedule
      containers:
      - name: e-one
        image: bash
        command: [ "top" ]
...
