---
kind: Pod
apiVersion: v1
metadata:
  name: b-pod
  labels:
    mysidlabs.com/app: k8s-demo
spec:
  volumes:
    - name: b-pvc-vol
      azureFile:
        secretName: azure-secret
        shareName: azure-storage
        readOnly: false
  containers:
    - name: b-bash
      image: bash
      imagePullPolicy: IfNotPresent
      command: [ "top" ]
      volumeMounts:
        - mountPath: "/tmp/b-pvc"
          name: b-pvc-vol
...
