---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: b-sc
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0775
  - file_mode=0775
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  storageAccount: ranstorageaccount
  skuName: Standard_LRS
  resourceGroup: SJT-Lab
