---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: a-ds
  labels:
    app: k8s-demo
spec:
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: a-one
        image: bash
        command: [ "top" ]
...
