---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    taranto.dev/app: k8s-demo
  name: a-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/app: a-dep
  template:
    metadata:
      labels:
        taranto.dev/app: a-dep
    spec:
      containers:
      - name: a-one
        image: bash
        command: [ "top" ]
...
