---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-demo
  name: a-dep-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-dep-multi
  template:
    metadata:
      labels:
        app: a-dep-multi
    spec:
      containers:
      - name: a-one
        image: bash
        command: [ "top" ]
      - name: a-two
        image: bash
        command: [ "sleep", "1000" ]
      - name: a-three
        image: bash
        command: [ "sleep", "1000" ]
...
