---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a-rs
  labels:
    taranto.dev/app: k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      taranto.dev/app: k8s-demo
  template:
    metadata:
      labels:
        taranto.dev/app: k8s-demo
    spec:
      containers:
      - name: a-one
        image: bash
        command: [ "top" ]
...
