---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: a-cronjob
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
spec:
  schedule: "*/3 * * * *"
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: a-one 
            image: staranto/k8s-demo-runner:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
...
