---
apiVersion: batch/v1
kind: Job
metadata:
  name: a-job
  labels:
    taranto.dev/app: k8s-demo
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: a-one 
        image: bash
        command: [ "bash" ]
        args: [ "-c",  "for x in {1..10}; do uptime; sleep 5; done"]
      restartPolicy: Never
...

