---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a-rs
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
    taranto.dev/example: a-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      taranto.dev/example: a-replicaset
  template:
    metadata:
      labels:
        taranto.dev/example: a-replicaset
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: a-one
        image: bash
        command: [ "top" ]
...
